### ISSUE TITLE
Missing configure_requires dep on EU::MM 6.64

### ISSUE THREAD

**Issue by autarch** [tomk3003/devel-cover-report-sonargeneric#1]
The `Makefile.PL` loads `ExtUtils::MakeMaker 6.64` but this version requirement is not reflected in the `META.json` that ships with the distro.

**Comment by autarch** [comment]
This isn't fixed by that commit. You need to specify EUMM deps in `CONFIGURE_REQUIRES`.

**Comment by tomk3003** [comment]
Sorry, copy and paste error. I'll fix it.
